name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Install Ruby and Bundler
        run: |
          brew install ruby
          gem install bundler

      - name: Install Fastlane
        run: bundle install

      - name: Run tests
        run: bundle exec fastlane tests
